version: '3.7'

services:
  nfg-util:
    image: node:18-alpine
    container_name: nfg-util
    user: '1000'
    working_dir: '/app'
    command: 'npm run docker-compose'
    tty: true
    stdin_open: true
    volumes:
      - '.:/app'
      - '${HOME}/.npmrc-automate_nfgutils:/app/.npmrc'
