version: '3.7'

services:
  change-vol-ownership:
    image: node:18-alpine3.18
    command: chown -R 1000:1000 /_triggers
    group_add:
      - '1000'
    volumes:
      - hh-triggers:/_triggers

  hh-util:
    volumes:
      - ./.docker/.npmrc-localRegistry:/app/.npmrc
      - hh-triggers:/_triggers/
    depends_on:
      # Wait for the ownership to change
      change-vol-ownership:
        condition: service_completed_successfully
    networks:
      - hh-util_registry

volumes:
  hh-triggers:
    name: hh-triggers
